spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cool_bank?serverTimezone=Asia/Seoul
    username: root
    password: 159624
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: debug
server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 30m